# Assignment 02

Dear Team Members,

I hope you are doing GREAT!

The following assignment is a step-by-step process to implement a multiclass classification using Iris classical dataset.
The idea of the current assignment is to intensify what we have learned in deep learning.

There are some new concepts and challenges that we will face in the current assignment, and we need to resolve each issue and move to the next step.

After the midterm, we will discuss part of the potential challenges. The assignment is easy to follow yet needs the patience to solve each question at a time.

**Note:**

Please note that every question has 0.5 and it provides five out of total ten marks for the assignment.

The video presentation, as you have done for Assignment 01, provides the rest of the mark, which is 5.

In short, 5 for coding + 5 for the video presentation = 10, but without YouTube presentation you receive no mark for the submission. In short, only submissions with YouTube link will be marked.


In [ ]:
#Student Name: Vedantsinh Gohel
#Student Id:101398199

In [ ]:
#00 The iris.csv file (Iris dataset) is located in the Assignment folder below the current ipynb file.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


 **Important Note:** We are NOT allowed to import the dataset from Keras. We need to upload the provided iris.csv file to colab from our Google Drive.

In [ ]:
#00 1st, upload the iris.csv into your Google Drive (your Colab folder).
import pandas as pd
import numpy as np

In [ ]:
#01-a Find the path of iris.csv file, and save it in a variable called fileName.
fileName = "/content/drive/MyDrive/ColabNotebooks/Assignment_02_iris.csv"

In [ ]:
#01-b Read the content of the iris.csv file and save it in a variable, named iris.
iris = pd.read_csv(fileName)

In [ ]:
#01-c Show the first 5 rows of the dataframe.
iris.head()


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

As you see, the last column contains strings. We want to convert these strings to integers,  and we can work with them easily in our Neural Network model.

setosa -> 0

versicolor -> 1

virginica -> 2

In [ ]:
#2-a Please convert the last column strings to integers, as
# setosa -> 0
# versicolor -> 1
# virginica ->
iris['species'] = iris['species'].map({'setosa':0,'versicolor':1,'virginica':2})

In [ ]:
#2-b Now, check the first 5 elements of the iris dataset once again:
iris.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
#03-a Select the first four columns of the dataframe as the Data and call the data x.
x= iris.iloc[:,0:4].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
#03-b Select the last column as the label and call it y.
y = iris.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#04 Now, it is the time to split the data (x) and the label (y) into training and testin segments,
#   and call them parts x_train,x_test,y_train,y_test.

In [ ]:
#04-a Please split the data, and label ito training and testing segments, while the size of test data is 20%,
#     and use randome_state = 123 to make all the answers similar in the whole class.
!pip install scikit-learn
from sklearn.model_selection import train_test_split

x_train, x_test , y_train ,y_test = train_test_split(x,y,test_size=0.2 , random_state=123)

In [ ]:
#04-b Please, check the first five rows of  x_train,x_test,y_train,y_test.
x_train[0:5]

x_test[0:5]

y_train[0:5]

y_test[0:5]

array([1, 2, 2, 1, 0])

In [ ]:
#04-c Check the length of the x_train and x_test. If the numbers are 120 & 30, AWESOME!
#     You are good to continue!
len(x_train)

len(x_test)

30

In [ ]:
#05-a Please, convert y_train and y_test into categorical, and call them
#     one_hot_train_labels, and one_hot_test_labels, respectively.
from tensorflow.keras.utils import to_categorical

one_hot_train_labels = to_categorical(y_train)
one_hot_test_labels = to_categorical(y_test)

In [ ]:
#06-a Please define a sequential model that contains 3 dense layers.
#     In the first and second layers, use 100 hidden units (neurons) and a 'relu' activation function.
#     For the last layer, we need to use 3 as the number of output,
#     and the reason is we have three classes (setosa -> 0, versicolor -> 1, virginica -> 2)
#     Also, please pick an appropriate activation function for the last layer.
#     (You already have guessed what could be the best when we have converted the labels to categorical.)


In [ ]:
from tensorflow.keras import models, layers

myModel = models.Sequential()
myModel.add(layers.Dense(100, activation='relu'))
myModel.add(layers.Dense(100, activation='relu'))
myModel.add(layers.Dense(3, activation='softmax'))

In [ ]:
#06-b Now, please compile your model using 'rmsprop', an appropriate loss function, and 'accuracy' for your metrics.

In [ ]:
myModel.compile(optimizer='rmsprop',loss = 'categorical_crossentropy', metrics=['accuracy'])

In [ ]:
#07-a Pleease fit your model using epoch=20, batch = 10.

In [ ]:
model1 = myModel.fit(x_train, one_hot_train_labels, epochs=20, batch_size=10)

Epoch 1/20
12/12 [==============================] - 1s 4ms/step - loss: 0.8405 - accuracy: 0.6167
Epoch 2/20
12/12 [==============================] - 0s 4ms/step - loss: 0.6189 - accuracy: 0.8000
Epoch 3/20
12/12 [==============================] - 0s 4ms/step - loss: 0.5050 - accuracy: 0.8750
Epoch 4/20
12/12 [==============================] - 0s 4ms/step - loss: 0.4372 - accuracy: 0.8833
Epoch 5/20
12/12 [==============================] - 0s 7ms/step - loss: 0.3904 - accuracy: 0.9083
Epoch 6/20
12/12 [==============================] - 0s 7ms/step - loss: 0.3348 - accuracy: 0.9167
Epoch 7/20
12/12 [==============================] - 0s 6ms/step - loss: 0.2994 - accuracy: 0.9417
Epoch 8/20
12/12 [==============================] - 0s 4ms/step - loss: 0.2607 - accuracy: 0.9500
Epoch 9/20
12/12 [==============================] - 0s 4ms/step - loss: 0.2674 - accuracy: 0.9250
Epoch 10/20
12/12 [==============================] - 0s 7ms/step - loss: 0.2270 - accuracy: 0.9417
Epoch 11/20
12/12 [

In [ ]:
#08-a Please calculate the result, evaluating your x_test, one_hot_test_label, and see how accurate your model works.

In [ ]:
test_loss1, test_acc1 = myModel.evaluate(x_test, one_hot_test_labels)
print("Test accuracy : ",test_acc1)

1/1 [==============================] - 1s 582ms/step - loss: 0.1862 - accuracy: 0.8667
Test accuracy :  0.8666666746139526


In [ ]:
#09-a Now, we repeate all we have done in #06-a with the following parameters:
#     In the first and second layers, use 10 hidden units (neurons) and a 'relu' activation function.
#     For the last layer, we need to use 3.

In [ ]:
myModel2 = models.Sequential()
myModel2.add(layers.Dense(10, activation='relu'))
myModel2.add(layers.Dense(10, activation='relu'))
myModel2.add(layers.Dense(3, activation='softmax'))

In [ ]:
#09-b Use the same setting as you have done for #06-b (compile phase using 'rmsprom' and et cetera)

In [ ]:
myModel2.compile(optimizer='rmsprop',loss = 'categorical_crossentropy', metrics=['accuracy'])

In [ ]:
#09-c Please fit your model using epoch=4, batch = 10.

In [ ]:
model2 = myModel2.fit(x_test,one_hot_test_labels, epochs=4, batch_size=10)

Epoch 1/4
3/3 [==============================] - 1s 9ms/step - loss: 1.9720 - accuracy: 0.2000
Epoch 2/4
3/3 [==============================] - 0s 14ms/step - loss: 1.6996 - accuracy: 0.2000
Epoch 3/4
3/3 [==============================] - 0s 8ms/step - loss: 1.5228 - accuracy: 0.2000
Epoch 4/4
3/3 [==============================] - 0s 9ms/step - loss: 1.4025 - accuracy: 0.2000


In [ ]:
#09-d Please calculate the result, evaluating your x_test, one_hot_test_label, and see how accurate your model works.

In [ ]:
test_loss2, test_acc2 = myModel2.evaluate(x_test, one_hot_test_labels)
print("Test accuracy : ",test_acc2)


1/1 [==============================] - 0s 259ms/step - loss: 1.3248 - accuracy: 0.2000
Test accuracy :  0.20000000298023224


In [ ]:
#10-a Please explain all you have learned from this assignment.
# Theese are some quiestions that you could answer:
#1 How the number of layers or hidden units could impact the accuracy of our model.
#2 Do we always suffer from overfitting?
#3 How can we find and manage overfitting?

1. The number of layers and hidden units in a neural network really matters for how well it learns from data. Adding more can help understand complex patterns better, improving accuracy, but too many can lead to memorizing useless details, hurting performance. Simplifying by reducing layers or units might make it easier to understand but could also miss important patterns, lowering accuracy.

2. Overfitting doesn't always happen, but it's like a bug in machine learning. It occurs when the model gets too fixated on the training data, mistaking noise for important patterns. Simple models are less likely to overfit, while complex ones with lots of parts are more at risk, especially with small datasets.

3. Dealing with overfitting involves splitting data into training and validation sets to spot if the model is overfitting, using techniques like regularization to keep it simple, dropout to prevent reliance on certain neurons, early stopping to halt training when performance declines, and sometimes simplifying the model by trimming layers or units to tame overfitting, albeit at the expense of some complexity.

In [ ]:
#10-b
# Please try different sessing as we did in #09
# You can change the number of layers, hidden units, compile parameters, number of epochs, batch_size... everything!
# Please change one parameter at a time.
# And share your experience.

In [ ]:
# Adjusting the number of hidden units
myModel3 = models.Sequential()
myModel3.add(layers.Dense(150, activation='relu'))
myModel3.add(layers.Dense(150, activation='relu'))
myModel3.add(layers.Dense(3, activation='softmax'))

# Compiling the model
myModel3.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

# Fitting the model
model3 = myModel3.fit(x_train, one_hot_train_labels, epochs=20, batch_size=10)

# Evaluating the model
test_loss3, test_acc3 = myModel3.evaluate(x_test, one_hot_test_labels)
print("Test accuracy with increased hidden units:", test_acc3)



Epoch 1/20
12/12 [==============================] - 2s 8ms/step - loss: 0.9117 - accuracy: 0.6083
Epoch 2/20
12/12 [==============================] - 0s 8ms/step - loss: 0.6257 - accuracy: 0.7250
Epoch 3/20
12/12 [==============================] - 0s 7ms/step - loss: 0.4944 - accuracy: 0.7917
Epoch 4/20
12/12 [==============================] - 0s 7ms/step - loss: 0.4260 - accuracy: 0.8333
Epoch 5/20
12/12 [==============================] - 0s 11ms/step - loss: 0.3504 - accuracy: 0.8917
Epoch 6/20
12/12 [==============================] - 0s 9ms/step - loss: 0.3110 - accuracy: 0.9167
Epoch 7/20
12/12 [==============================] - 0s 8ms/step - loss: 0.2638 - accuracy: 0.9250
Epoch 8/20
12/12 [==============================] - 0s 6ms/step - loss: 0.2234 - accuracy: 0.9417
Epoch 9/20
12/12 [==============================] - 0s 7ms/step - loss: 0.1964 - accuracy: 0.9500
Epoch 10/20
12/12 [==============================] - 0s 8ms/step - loss: 0.1760 - accuracy: 0.9500
Epoch 11/20
12/12 

---
# Deliverables:
1. Please, submit the current ipynb file with your responses.
2. Please record and upload to YouTube a 5 to 10 minutes video recorded clip, describing all you have done. If you go beyond 10 minutes, it is fine. The mentioned time range is to show how the scale of the assignment could be.

Notes:
- In your submission, YOU MUST SUBMIT A LINK TO YOUR YOUTUBE VIDEO as a COMENTS SUBMISSION SECTION on your D2L SUBMISSION. Omitting this comment will result in a 0% for your total mark.

- To get the 5% of the (coding) mark, you need to submit a YouTube video that scrolls through your code, explaining every single line of your code.

Then submit the link to the uploaded YouTube video in the **Comments Submision section**.  


**Summary:**

In short, what we need to submit are:

a)	The current **ipynb file** that contains all the code (5 marks).

b)	The **YouTube link** of your recorded video in the
**Comments Submission section** (5 marks).

Zero for submissions, without YouTube video explanation.



Wish you only the best, Dear Team Members!

Reza
